// <auto-generated />
namespace Chinook.EF.CodeFirst.DataAcces.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class scriptInit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(scriptInit));
        
        string IMigrationMetadata.Id
        {
            get { return "201809190135286_scriptInit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
